- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: kalyani
  become: false

  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "kalyaniv2001/calculator_using_python"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Running container
      shell: docker run -it -d --name python_calculator kalyaniv2001/calculator_using_python
